spring.application.name=study-website

spring.datasource.url=jdbc:postgresql://localhost:5432/studydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.skip.in-tests=false

logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.apache.coyote.http11=DEBUG


spring.sql.init.mode=always


